version: '3.7'
services:
  kms:
    restart: unless-stopped

  backend:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./backend/src:/app/src

  frontend:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
